development:
    mongodb:
      host: "localhost"
    selenium_chrome:
      host: "http://localhost:4444/wd/hub"
    selenium_firefox:
      host: "http://localhost:4445/wd/hub"

production:
    mongo:
      host: "mongoprod"
    selenium_chrome:
      host: "http://selenium:4444/wd/hub"
    selenium_firefox:
      host: "http://selenium:4445/wd/hub"